"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
\n$character
"""

add_newline = true

palette = 'colors'

[palettes.colors]
aqua = '#689d6a'
orange = '#d65d0e'

[line_break]
disabled = true

[git_branch]
format = '[  $branch ](bg:aqua)'

[directory]
format = "[  $path ](bg:orange)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
